### ISSUE TITLE
Looks like the site is not working

### ISSUE THREAD

**Issue by stokito** [RemoteSlide/remote-sli.de#5]
Hi, thank you for your extention. I tried it from my iPhone 6 but it looks like it not working.
I used three different browsers and in some of them I got some gray screen and on anothers I got "Waiting for host to connect".
Gould you please check yourself if it works?

**Comment by InventivetalentDev** [comment]
It works fine with my android phone & chrome. Unfortunately I don't own an iPhone so I can't really test it on there.  
Did you use the chrome extension or a bookmark on your computer?
